const axios = require("axios");

const proverbs = {
  en: [
    "A bird in the hand is worth two in the bush.",
    "A cat may look at a king.",
    "A chain is only as strong as its weakest link.",
    "A change is as good as a rest.",
    "A drowning man will clutch at a straw.",
    "A fair day's work for a fair day's pay.",
    "A fool and his money are soon parted.",
    "A friend in need is a friend indeed.",
    "A golden key can open any door.",
    "A good beginning makes a good ending.",
    "A good man is hard to find.",
    "A house divided against itself cannot stand.",
    "A house is not a home.",
    "A journey of a thousand miles begins with a single step.",
    "A leopard cannot change its spots.",
    "A Leopard can't change its spots a person can't change who they are.",
    "A little knowledge is a dangerous thing.",
    "A little of what you fancy does you good.",
    "A man who is his own lawyer has a fool for his client.",
    "A man with a hammer sees every problem as a nail.",
    "A miss is as good as a mile.",
    "A new broom sweeps clean, but an old one knows where the dirt is.",
    "A nod is as good as a wink to a blind horse.",
    "A penny saved is a penny earned.",
    "A person is known by the company he keeps.",
    "A picture is worth a thousand words.",
    "A place for everything and everything in its place.",
    "A poor workman always blames his tools.",
    "A problem shared is a problem halved.",
    "A prophet is not recognized in his own land.",
    "A rising tide lifts all boats.",
    "A rolling stone gathers no moss.",
    "A soft answer turneth away wrath.",
    "A stitch in time saves nine.",
    "A swarm in May is worth a load of hay; a swarm in June is worth a silver spoon; but a swarm in July is not worth a fly.",
    "A thing of beauty is a joy forever.",
    "A trouble shared is a trouble halved.",
    "A volunteer is worth twenty pressed men.",
    "A watched pot never boils.",
    "A woman's place is in the home.",
    "A man works from sun to sun but a woman's work is never done.",
    "A word to the wise is enough.",
    "Absence makes the heart grow fonder.",
    "Absolute power corrupts absolutely.",
    "Accidents will happen.",
    "Actions speak louder than words.",
    "Adversity makes strange bedfellows.",
    "All good things come to he who waits.",
    "All good things must come to an end.",
    "All is grist that comes to the mill.",
    "All roads lead to Rome.",
    "All that glitters is not gold.",
    "All the world loves a lover.",
    "All things come to those who wait.",
    "All things must pass.",
    "All work and no play makes Jack a dull boy.",
    "All you need is love.",
    "All is fair in love and war.",
    "All is for the best in the best of all possible worlds.",
    "All is well that ends well.",
    "An apple a day keeps the doctor away.",
    "An army marches on its stomach.",
    "An Englishman's home is his castle.",
    "Another day, another dollar.",
    "An ounce of prevention is worth a pound of cure.",
    "Any port in a storm.",
    "Any publicity is good publicity.",
    "April showers bring forth May flowers.",
    "As you make your bed, so you must lie upon it.",
    "As you sow so shall you reap.",
    "Ask a silly question and you will get a silly answer.",
    "Ask my companion if I be a thief.",
    "Ask no questions and hear no lies.",
    "Attack is the best form of defense.",
    "Bad news travels fast.",
    "Barking dogs seldom bite.",
    "Beauty is in the eye of the beholder.",
    "Beauty is only skin deep.",
    "Beggars should not be choosers.",
    "Behind every great man, there is a great woman.",
    "Better late than never.",
    "Better safe than sorry.",
    "Better the Devil you know than the Devil you do not.",
    "Better to have loved and lost than never to have loved at all.",
    "Better to light one candle than to curse the darkness.",
    "Better to remain silent and be thought a fool than to speak and remove all doubt.",
    "Better wear out than rust out.",
    "Beware of Greeks bearing gifts.",
    "Big fish eat little fish.",
    "Birds of a feather flock together.",
    "Blood is thicker than water.",
    "Boys will be boys.",
    "Brevity is the soul of wit.",
    "Business before pleasure.",
    "Caesar's wife must be above suspicion.",
    "Careless talk costs lives.",
    "Charity begins at home.",
    "Cheats never prosper.",
    "Children should be seen and not heard.",
    "Christmas comes but once a year.",
    "Cleanliness is next to godliness.",
    "Clothes make the man.",
    "Cold hands, warm heart.",
    "Comparisons are odious.",
    "Count your blessings.",
    "Courage is the measure of a Man, Beauty is the measure of a Woman.",
    "Cowards may die many times before their death.",
    "Crime does not pay.",
    "Cut your coat according to your cloth.",
    "Curiosity killed the cat.",
    "Dead men tell no tales.",
    "Devil take the hindmost.",
    "Discretion is the better part of valour.",
    "Do as I say, not as I do.",
    "Do as you would be done by.",
    "Do unto others as you would have them do unto you.",
    "Do not bite the hand that feeds you.",
    "Do not burn your bridges behind you.",
    "Do not cast your pearls before swine.",
    "Do not cry over spilt milk.",
    "Do not change horses in midstream.",
    "Do not count your chickens before they are hatched.",
    "Do not cross the bridge till you come to it.",
    "Do not cut off your nose to spite your face.",
    "Do not keep a dog and bark yourself.",
    "Do not let the bastards grind you down.",
    "Do not look a gift horse in the mouth.",
    "Do not make a mountain of a mole hill.",
    "Do not meet troubles half-way.",
    "Do not put all your eggs in one basket.",
    "Do not put the cart before the horse.",
    "Do not put new wine into old bottles.",
    "Do not rock the boat.",
    "Do not spoil the ship for a ha'pworth of tar.",
    "Do not throw pearls to swine.",
    "Do not teach your Grandmother to suck eggs.",
    "Do not throw the baby out with the bathwater.",
    "Do not try to walk before you can crawl.",
    "Do not upset the apple-cart.",
    "Do not wash your dirty linen in public.",
    "Doubt is the beginning, not the end, of wisdom.",
    "Early to bed and early to rise, makes a man healthy, wealthy and wise.",
    "East is east, and west is west.",
    "East, west, home is best.",
    "Easy come, easy go.",
    "Eat breakfast as a king, lunch as a merchant and supper as a beggar.",
    "Eat, drink and be merry, for tomorrow we die.",
    "Empty vessels make the most noise.",
    "Enough is as good as a feast.",
    "Enough is enough.",
    "Even a worm will turn.",
    "Every cloud has a silver lining.",
    "Every dog has his day.",
    "Every Jack has his Jill.",
    "Every little bit helps.",
    "Every man for himself, and the Devil take the hindmost.",
    "Every man has his price.",
    "Every picture tells a story.",
    "Every stick has two ends.",
    "Everybody wants to go to heaven but nobody wants to die.",
    "Everything comes to those who wait.",
    "Fact is stranger than fiction.",
    "Failing to plan is planning to fail.",
    "Faint heart never won fair lady.",
    "Fair exchange is no robbery.",
    "Faith will move mountains.",
    "Familiarity breeds contempt.",
    "Feed a cold and starve a fever.",
    "Fight fire with fire.",
    "Finders keepers, losers weepers.",
    "Fine words butter no parsnips.",
    "First come, first served.",
    "First impressions are the most lasting.",
    "First things first.",
    "Fish always stinks from the head downwards.",
    "Fish and guests smell after three days.",
    "Flattery will get you nowhere.",
    "Fools rush in where angels fear to tread.",
    "For want of a nail the shoe was lost; for want of a shoe the horse was lost; and for want of a horse the man was lost.",
    "Forewarned is forearmed.",
    "Fortune favours the brave.",
    "Genius is an infinite capacity for taking pains.",
    "Give a dog a bad name and hang him.",
    "Give a man a fish and you feed him for a day. Teach a man to fish and you feed him for a lifetime.",
    "Give a man rope enough and he will hang himself.",
    "Give credit where credit is due.",
    "Give him an inch and he will take a mile.",
    "God helps those who help themselves.",
    "Good fences make good neighbours.",
    "Good talk saves the food.",
    "Good things come to those who wait.",
    "Great minds think alike.",
    "Half a loaf is better than no bread.",
    "Handsome is as handsome does.",
    "Hard cases make bad law.",
    "Hard work never did anyone any harm.",
    "Haste makes waste.",
    "He that goes a-borrowing, goes a-sorrowing.",
    "He who can does, he who cannot, teaches.",
    "He who fights and runs away may live to fight another day.",
    "He who hesitates is lost.",
    "He who laughs last laughs best.",
    "He who lives by the sword shall die by the sword.",
    "He who loves the world as his body may be entrusted with the empire.",
    "He who makes a beast out of himself gets rid of the pain of being a man.",
    "He who pays the piper calls the tune.",
    "He who knows does not speak. He who speaks does not know.",
    "He who sups with the Devil should have a long spoon.",
    "Hell hath no fury like a woman scorned.",
    "Hindsight is always twenty-twenty.",
    "History repeats itself.",
    "Home is where the heart is.",
    "Honesty is the best policy.",
    "Hope springs eternal.",
    "Horses for courses.",
    "Hunger never knows the taste, sleep never knows the comfort.",
    "If anything can go wrong, it will.",
    "If a job is worth doing, it is worth doing well.",
    "If at first you do not succeed, try, try again.",
    "If God had meant us to fly, he would have given us wings.",
    "If ifs and ands were pots and pans, there would be no work for tinkers.",
    "If life deals you lemons, make lemonade.",
    "If the cap fits, wear it.",
    "If the mountain will not come to Mohammed, then Mohammed must go to the mountain.",
    "If we're not back by dawn, call the President.",
    "If wealth is lost, nothing is lost. If health is lost, something is lost. If character is lost, everything is lost.",
    "If wishes were horses, beggars would ride.",
    "If you're growing in Age,then you're nearing to the Graveyard.",
    "If you cannot be good, be careful.",
    "If you cannot beat them, join them.",
    "If you cannot stand the heat, get out of the kitchen.",
    "If you give a mouse a cookie, he'll always ask for a glass of milk.",
    "If you think that you know everything, then you're a Jack ass.",
    "If you lie down with dogs, you will get up with fleas.",
    "If you pay peanuts, you get monkeys.",
    "If you steal from one author, it is plagiarism; if you steal from many, it is research.",
    "If you want a thing done well, do it yourself.",
    "If you have never seen the bottom of the tree, you cannot know how tall it stands.",
    "Imitation is the sincerest form of flattery.",
    "In for a penny, in for a pound.",
    "In the kingdom of the blind, the one eyed man is king.",
    "In the midst of life, we are in death.",
    "Into every life a little rain must fall.",
    "It goes without saying.",
    "It is all grist to the mill.",
    "It is an ill wind that blows no one any good.",
    "It is best to be on the safe side.",
    "It is better to give than to receive.",
    "It is better to have loved and lost than never to have loved at all.",
    "It is better to cultivate a Land with two Bulls, rather working under Boss who never gives Wage when asked.",
    "It is better to light a candle than curse the darkness.",
    "It is better to travel hopefully than to arrive.",
    "It is easy to be wise after the event.",
    "It is never too late.",
    "It is no use crying over spilt milk.",
    "It is no use locking the stable door after the horse has bolted.",
    "It is the early bird that gets the worm.",
    "It is the empty can that makes the most noise.",
    "It is the squeaky wheel that gets the grease.",
    "It never rains but it pours.",
    "It takes a thief to catch a thief.",
    "It needs a Hundred Lies to cover a Single Lie.",
    "It takes all sorts to make a world.",
    "It takes one to know one.",
    "It takes two to tango.",
    "I'm going to have to give you the pink slip.",
    "Jack of all trades, master of none.",
    "Jack of all trades, master of some.",
    "Judge not, that ye be not judged.",
    "Keep your chin up.",
    "Keep your friends close and your enemies closer.",
    "Keep your powder dry.",
    "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.",
    "Knowledge is power, guard it well.",
    "Laugh before breakfast, cry before supper.",
    "Laugh and the world laughs with you, weep and you weep alone.",
    "Laughter is the best medicine.",
    "Least said, soonest mended.",
    "Less is more.",
    "Let bygones be bygones.",
    "Let not the sun go down on your wrath.",
    "Let sleeping dogs lie.",
    "Let the buyer beware.",
    "Let the dead bury the dead.",
    "Let the punishment fit the crime.",
    "Let well alone.",
    "Let your hair down.",
    "Life begins at forty.",
    "Life is not all beer and skittles.",
    "Life is what you make it.",
    "Lightning never strikes twice in the same place.",
    "Like father, like son.",
    "Little pitchers have big ears.",
    "Little strokes fell great oaks.",
    "Little things please little minds.",
    "Live and let live.",
    "Live for today, for tomorrow never comes.",
    "Look before you leap.",
    "Love is blind.",
    "Love of money is the root of all kinds of evil.",
    "Love makes the world go around.",
    "Love will find a way.",
    "Make hay while the sun shines.",
    "Make love not war.",
    "Man does not live by bread alone.",
    "Manners maketh man.",
    "Many a little makes a mickle.",
    "Many a mickle makes a muckle.",
    "Many a true word is spoken in jest.",
    "Many hands make light work.",
    "March comes in like a lion and goes out like a lamb.",
    "Marriages are made in heaven.",
    "Marry in haste, repent at leisure.",
    "Men get spoiled by staying, Women get spoiled by wandering.",
    "Might is right.",
    "Might makes light.",
    "Mighty oaks from little acorns grow.",
    "Milking the bull.",
    "Misery loves company.",
    "Moderation in all things.",
    "Monday's child is fair of face, Tuesday's child is full of grace, Wednesday's child is full of woe, Thursday's child has far to go, Friday's child is loving and giving, Saturday's child works hard for its living, and a child that is born on the Sabbath day is fair and wise and good and gay.",
    "Money does not grow on trees.",
    "Money earned by deceit, goes by deceit.",
    "Money is not everything.",
    "Money makes the world go around.",
    "Money talks.",
    "Money makes many things, but also makes devil dance.",
    "More haste, less speed.",
    "Music has charms to soothe the savage beast.",
    "Nature abhors a vacuum.",
    "Never reveal a man's wage, and woman's age.",
    "Necessity is the mother of invention.",
    "Needs must when the devil drives.",
    "Never cast a clout until May be out.",
    "Never give a sucker an even break.",
    "Never judge a book by its cover.",
    "Never let the sun go down on your anger.",
    "Never look a gift horse in the mouth.",
    "Never put off until tomorrow what you can do today.",
    "Never speak ill of the dead.",
    "Never say never.",
    "Never tell tales out of school.",
    "Nine tailors make a man.",
    "No guts, no glory.",
    "No man can serve two masters.",
    "No man is an island.",
    "No names, no pack-drill.",
    "No news is good news.",
    "No one can make you feel inferior without your consent.",
    "No pain, no gain.",
    "No rest for the wicked.",
    "Nothing is certain but death and taxes.",
    "Nothing succeeds like success.",
    "Nothing ventured, nothing gained.",
    "Once a witch always a witch.",
    "Oil and water do not mix.",
    "Old soldiers never die; they just fade away.",
    "Once a thief, always a thief.",
    "Once bitten, twice shy.",
    "One good turn deserves another.",
    "One half of the world does not know how the other half lives.",
    "One hand washes the other.",
    "One man's meat is another man's poison.",
    "One might as well be hanged for a sheep as a lamb.",
    "One law for the rich and another for the poor.",
    "One swallow does not make a summer.",
    "One who believes in Sword, dies by the Sword.",
    "One year's seeding makes seven years weeding.",
    "Only fools and horses work.",
    "Opportunity never knocks twice at any man's door.",
    "Out of sight, out of mind.",
    "Over greedy man, over wrathful woman will never flourish.",
    "Parsley seed goes nine times to the Devil.",
    "Patience is a virtue.",
    "Pearls of wisdom.",
    "Penny wise and pound foolish.",
    "People who live in glass houses should not throw stones.",
    "Physician, heal thyself.",
    "Possession is nine-tenths of the law.",
    "Power corrupts; absolute power corrupts absolutely.",
    "Practice makes perfect.",
    "Practice what you preach.",
    "Prevention is better than cure.",
    "Pride goes before a fall.",
    "Procrastination is the thief of time.",
    "Put your best foot forward.",
    "Put your money where your mouth is.",
    "Red sky at night shepherds delight; red sky in the morning, shepherds warning.",
    "Revenge is a dish best served cold.",
    "Revenge is sweet.",
    "Rome was not built in a day.",
    "Right or wrong, my country.",
    "See a penny and pick it up, all the day you will have good luck; see a penny and let it lay, bad luck you will have all day.",
    "See no evil, hear no evil, speak no evil.",
    "Seeing is believing.",
    "Seek and ye shall find.",
    "Set a thief to catch a thief.",
    "Shiny are the distant hills.",
    "Shrouds have no pockets.",
    "Silence is golden.",
    "Slow and steady wins the race.",
    "Slow but sure.",
    "Softly, softly, catchee monkey.",
    "Sometimes we are the student. Sometimes we are the master. And sometimes we are merely the lesson.",
    "Spare the rod and spoil the child.",
    "Speak as you find.",
    "Speak softly and carry a big stick.",
    "Speech is silver.",
    "Sticks and stones may break my bones, but words will never hurt me.",
    "Still waters run deep.",
    "Strike while the iron is hot.",
    "Stupid is as stupid does.",
    "Success has many fathers, while failure is an orphan.",
    "Take care of the pennies, and the pounds will take care of themselves.",
    "Talk is cheap.",
    "Talk of the Devil, and he is bound to appear.",
    "Tell me who your friends are, and I'll tell you who you are.",
    "Tell the truth and shame the Devil.",
    "That which does not kill us makes us stronger.",
    "The age of miracles is past.",
    "The apple never falls far from the tree.",
    "The best defence is a good offence.",
    "The best-laid schemes of mice and men often go awry.",
    "The best things in life are free.",
    "The bigger they are, the harder they fall.",
    "The boy is father to the man.",
    "The bread never falls but on its buttered side.",
    "The child is the father of the man.",
    "The cobbler always wears the worst shoes.",
    "The course of true love never did run smooth.",
    "The customer is always right.",
    "The darkest hour is just before the dawn.",
    "The Devil finds work for idle hands to do.",
    "The Devil looks after his own.",
    "The early bird catches the worm.",
    "The end justifies the means.",
    "The exception which proves the rule.",
    "The female of the species is more deadly than the male.",
    "The good die young.",
    "The grass is always greener on the other side of the fence.",
    "The hand that rocks the cradle rules the world.",
    "The husband is always the last to know.",
    "The innocent seldom find an uncomfortable pillow.",
    "The labourer is worthy of his hire.",
    "The leopard does not change his spots.",
    "The longest day must have an end.",
    "The longest journey starts with a single step.",
    "The moon is made of green cheese.",
    "The more the merrier.",
    "The more things change, the more they stay the same.",
    "The only way to understand a woman is to love her.",
    "The pen is mightier than the sword.",
    "The proof of the pudding is in the eating.",
    "The road to Hell is paved with good intentions.",
    "The shoemaker's son always goes barefoot.",
    "The squeaking wheel gets the grease.",
    "The straw that broke the camel's back.",
    "The way to a man's heart is through his stomach.",
    "There ain't no such thing as a free lunch.",
    "There are more ways of killing a cat than choking it with cream.",
    "There are none so blind as those that will not see.",
    "There are two sides to every question.",
    "There but for the grace of God go I.",
    "There is an exception to every rule.",
    "There are always more fish in the sea.",
    "There is honour among thieves.",
    "There is many a good tune played on an old fiddle.",
    "There is many a slip 'twixt cup and lip.",
    "There is more than one way to skin a cat.",
    "There is no accounting for tastes.",
    "There is no fool like an old fool.",
    "There is no place like home.",
    "There is no smoke without fire.",
    "There is no such thing as a free lunch.",
    "There is no such thing as bad publicity.",
    "There is no time like the present.",
    "There is none so blind as those who will not see.",
    "There's none so deaf as those who will not hear.",
    "There is nowt so queer as folk.",
    "There is one born every minute.",
    "There is safety in numbers.",
    "They that sow the wind shall reap the whirlwind.",
    "Third time is a charm.",
    "Those who do not learn from history are doomed to repeat it.",
    "Those who live in glass houses should not throw stones.",
    "Those who sleep with dogs will rise with fleas.",
    "Time and tide wait for no man.",
    "Time flies.",
    "Time is a great healer.",
    "Time is money.",
    "Time will tell.",
    "’Tis better to have loved and lost than never to have loved at all.",
    "To be worn out is to be renewed.",
    "To each his own.",
    "To err is human, to forgive divine.",
    "To the victor go the spoils.",
    "To travel hopefully is a better thing than to arrive.",
    "Tomorrow is another day.",
    "Tomorrow never comes.",
    "Too many cooks spoil the broth.",
    "Truth is stranger than fiction.",
    "Truth will out.",
    "Two blacks do not make a white.",
    "Two heads are better than one.",
    "Two is company, but three is a crowd.",
    "Two wrongs do not make a right.",
    "Variety is the spice of life.",
    "Walk softly but carry a big stick.",
    "Walnuts and pears you plant for your heirs.",
    "Waste not, want not.",
    "What cannot be cured must be endured.",
    "What goes around, comes around.",
    "What goes up must come down.",
    "What you lose on the swings you gain on the roundabouts.",
    "What is sauce for the goose is sauce for the gander.",
    "When in Rome, do as the Romans do.",
    "When it rains it pours.",
    "When the cat is away, the mice will play.",
    "When the going gets tough, the tough get going.",
    "When the oak is before the ash, then you will only get a splash; when the ash is before the oak, then you may expect a soak.",
    "When three women gather, it becomes noisy.",
    "What the eye does not see, the heart does not grieve over.",
    "Where there is a will there is a way.",
    "Where there is muck there is brass.",
    "Whether you think you can, or you think you can't, you're right.",
    "While there is life there is hope.",
    "Whom the Gods love die young.",
    "Why keep a dog and bark yourself?",
    "With a responsibility comes great power.",
    "Woman is the root of both good and evil.",
    "Wonders will never cease.",
    "Work expands so as to fill the time available.",
    "Worrying never did anyone any good.",
    "You are never too old to learn.",
    "You are what you eat.",
    "You can have too much of a good thing.",
    "You can lead a horse to water, but you cannot make it drink.",
    "You cannot have your cake and eat it too.",
    "You cannot get blood out of a stone.",
    "You cannot make a silk purse from a sow's ear.",
    "You cannot make an omelette without breaking eggs.",
    "You cannot make bricks without straw.",
    "You cannot run with the hare and hunt with the hounds.",
    "You cannot teach an old dog new tricks.",
    "You cannot judge a book by its cover.",
    "You cannot win them all.",
    "You catch more flies with honey than with vinegar.",
    "You pay your money and you take your choice.",
    "Youth is wasted on the young.",
    "You must have rocks in your head."
  ],
  pt: [
    "A ambição cerra o coração.",
    "A apressada pergunta, vagarosa resposta.",
    "A ave de rapina não canta.",
    "A barriga não tem fiador.",
    "A boa mão, do Rocim faz cavalo; e a ruim, do Cavalo faz Rocim.",
    "A boca do ambicioso só se fecha com terra da sepultura.",
    "A boda e a baptizado não vás sem ser convidado.",
    "A cada Bacorinho, vem seu S. Martinho.",
    "A cada boca uma sopa.",
    "A cadela, com pressa, pariu os cachorros cegos.",
    "A campo fraco, Lavrador forte.",
    "A casamento e baptizado, não vás sem ser convidado.",
    "A cavalo dado não se olha o dente.",
    "A chuva de S. João, bebe o Vinho e come o Pão.",
    "A chuva e o frio, metem a Lebre a caminho.",
    "A conselho amigo, não feches o postigo.",
    "A culpa morreu solteira.",
    "A desgraça não marca encontro.",
    "A encomenda é igual ao cabaz.",
    "A espada e o anel, segundo a mão em que estiverem.",
    "A falta do amigo há-de-se conhecer mas não aborrecer.",
    "A fama longe soa. E mais depressa a má que a boa.",
    "A fome é a melhor cozinheira.",
    "A fome é boa mostarda.",
    "A fome é o melhor tempero.",
    "A fome faz sair o lobo do mato.",
    "A galinha da vizinha é sempre melhor que a minha.",
    "A ganhar se perde e a perder se ganha.",
    "A gosto danado, o doce é amargo.",
    "A ignorância e o vento são do maior atrevimento.",
    "A justiça tarda mas não falha.",
    "A Laranja, de manhã é Ouro, de tarde é Prata, e à noite mata.",
    "A lei é dura, mas é para se cumprir.",
    "A melhor Cozinheira, é a azeiteira.",
    "A Morte abre a porta da Fama e fecha a da Inveja.",
    "A mulher, sem pôr o pé faz pegada.",
    "A necessidade aguça o engenho.",
    "A necessidade não tem lei.",
    "A noite é boa conselheira.",
    "A nuvem passa, mas a chuva fica.",
    "A ocasião faz o ladrão.",
    "A ociosidade é mãe de todos os vícios.",
    "A palavra é de prata e o silêncio é de ouro.",
    "A pedra e a palavra, não se recolhe depois de deitada.",
    "A Pescada de Janeiro, vale um carneiro.",
    "A pintura e a peleja, de longe se veja.",
    "A pobreza não é vileza, nem a riqueza nobreza.",
    "A preguiça é a mãe de todos os vícios.",
    "A preguiça morre à sede, andando a boiar.",
    "A pressa é inimiga da perfeição.",
    "A primeira, qualquer cai. À segunda cai quem quer.",
    "A quem do seu foi mau despenseiro, não fies o teu dinheiro.",
    "A quem tudo quer saber, nada se lhe diz.",
    "A razão e a verdade fogem quando ouvem disputas.",
    "A rir se corrigem os costumes.",
    "A roupa suja lava-se em casa.",
    "A união faz a força.",
    "A vaidade é o espelho dos tolos.",
    "A valentia com os fracos, só cobardia revela.",
    "A ventre farto o mel amarga.",
    "A verdade é como o azeite: vem sempre ao de cima.",
    "A vozes loucas, orelhas moucas.",
    "Abril frio e molhado, enche o celeiro e farta o gado.",
    "Abril, Abril, está cheio o covil.",
    "Agosto tem a culpa, e Setembro leva a fruta.",
    "Água de Fevereiro, mata o Onzeneiro.",
    "Água de Julho, no rio não faz barulho.",
    "Água detida é má para a bebida.",
    "Água e vento são meio sustento.",
    "Água mole em pedra dura, tando dá até que fura.",
    "Águas da Ascensão, das palhas fazem Grão.",
    "Águas passadas não movem Moinhos.",
    "Águas verdadeiras, por S. Mateus as primeiras.",
    "Aí por Santana, limpa a pragana.",
    "Ainda que mude a pele a Raposa, seu natural desponja.",
    "Albarda-se o burro à vontade do dono.",
    "Almoço cedo, faz carne e sebo; almoço tarde, nem sebo nem carne.",
    "Alto mar e não de vento, não promete seguro o tempo.",
    "Amigo diligente, é melhor que parente.",
    "Amigo disfarçado, inimigo dobrado.",
    "Amigo que não presta e faca que não corta: que se percam, pouco importa.",
    "Amigo verdadeiro vale mais do que dinheiro.",
    "Amigo, vinho e azeite o mais antigo.",
    "Amigos, amigos, negócios à parte.",
    "Amor com amor se paga.",
    "Amor de pais não há jamais.",
    "Amor querido, amor batido.",
    "Amores arrufados, amores dobrados.",
    "Ande o frio por onde andar, no Natal cá vem parar.",
    "Ande por onde andar o Verão, há-de vir no S. João.",
    "Ano de nevão, ano de pão.",
    "Ano de neve, paga o que deve.",
    "Antes caia do cu do que do alforge.",
    "Antes cegues que mal vejas.",
    "Antes martelo que bigorna.",
    "Antes mau ano que mau vizinho.",
    "Antes minha face com fome amarela, que vergonha nela.",
    "Antes que te cases, vê o que fazes.",
    "Antes quebrar que torcer.",
    "Antes quero Asno que me leve, que Cavalo que me derrube.",
    "Ao arrendar cantar e ao pagar chorar.",
    "Ao bebado e ao tolo, dá-se o caminho todo.",
    "Ao bom amigo, com teu pão e teu vinho.",
    "Ao bom pagador não dói o penhor.",
    "Ao Diabo e à mulher nunca falta que fazer.",
    "Ao Fevereiro e ao rapaz, perdoa tudo quanto faz.",
    "Ao homem de esforço a fortuna lhe põe ombro.",
    "Ao homem ousado a fortuna dá a mão.",
    "Ao menino e ao borracho põe Deus a mão por baixo.",
    "Ao pé do pano é que se talha a obra.",
    "Ao quinto dia verás que mês terás.",
    "Ao rico mil amigos se deparam, ao pobre seus irmãos o desamparam.",
    "Ao rico não devas e ao pobre não peças.",
    "Ao rico não faltes, ao pobre não prometas.",
    "Apanha com o cajado quem se mete onde não é chamado.",
    "Apanha-se mais depressa um mentiroso do que um coxo.",
    "Apanham-se mais moscas com mel do que com fel.",
    "Apressado come cru.",
    "Aproveite Fevereiro quem folgou em Janeiro.",
    "Aquele que me tira do perigo, é meu amigo.",
    "Aquilo que sabe bem, ou faz mal ou é pecado.",
    "Arco de teixo duro de armar e fraco para disparar.",
    "Arco sempre armado, ou frouxo ou quebrado.",
    "Arrenda a vinha e o pomar se os queres desgraçar.",
    "As aparências iludem.",
    "As boas contas fazem os bons amigos.",
    "As cadelas apressadas parem cães tortos.",
    "As favas, Maio as dá, Maio as leva.",
    "As obras falam, as palavras calam.",
    "As palavras são como as cerejas, vêm umas atrás das outras.",
    "As palavras voam, a escrita fica.",
    "As paredes têm ouvidos.",
    "As sopas e os amores, os primeiros são os melhores.",
    "Às vezes não se respeita o burro, mas a argola a que ele está amarrado.",
    "Assim como vires o tempo de Santa Luzia ao Natal, assim estará o ano mês a mês até final.",
    "Até ao lavar dos cestos é vindima.",
    "Até ao Natal um saltinho de pardal.",
    "Até S. Pedro abre rego e fecha rego.",
    "Até S. Pedro tem a vinha medo.",
    "Atrás de mim virá, quem de mim bem dirá.",
    "Ave que canta demais não sabe fazer o ninho.",
    "Ave só não faz ninho.",
    "Azeite de cima, mel do fundo e vinho do meio.",
    "Barco parado, não faz viagem.",
    "Barriga cheia, companhia desfeita.",
    "Besta grande, Cavalo de pau.",
    "Boa amizade, segundo parentesco.",
    "Boa cepa, Maio a deita.",
    "Boa fama granjeia quem não diz mal da vida alheia.",
    "Bocado comido não faz amigo.",
    "Boda molhada, boda abençoada.",
    "Bodas em Março é ser madraço.",
    "Boi luzidio nunca tem fastio.",
    "Boi velho com os ossos lavra.",
    "Bolsa despejada, casa amargurada.",
    "Bolsa leve, coração pesado.",
    "Bom é saber calar até ser tempo de falar.",
    "Bom rei, se quereis que vos sirva, dai-me de comer.",
    "Bom serás, se morto estás.",
    "Burro com fome, cardos come.",
    "Burro que geme, carga não teme.",
    "Burro velho não toma andadura; e se a toma, pouco dura.",
    "Burro velho, mais vale matá-lo que ensiná-lo.",
    "Burro velho, não aprende línguas.",
    "Cabrito de um mês, queijo de três.",
    "Cada cabeça sua sentença.",
    "Cada cor, seu paladar.",
    "Cada macaco no seu galho.",
    "Cada maluco com a sua mania.",
    "Cada terra com seu uso cada roca com seu fuso.",
    "Cada um por si, Deus por todos.",
    "Cada um puxa a brasa para a sua sardinha.",
    "Cada um sabe as linhas com que se cose.",
    "Cada um sabe de si e Deus sabe de todos",
    "Cada um vê mal ou bem, conforme os olhos que tem.",
    "Calças brancas em Janeiro, sinal de pouco dinheiro.",
    "Cama no chão, cama de cão.",
    "Candeia que vai à frente alumia duas vezes.",
    "Candelária chovida, à candeia dá vida.",
    "Cansa quem dá e mais cansa quem toma.",
    "Cão de raça não usa coleira.",
    "Cão que ladra não morde.",
    "Carga leve, longe pesa.",
    "Carnaval na eira, Páscoa à lareira.",
    "Casa de Duque nunca pediu.",
    "Casa de fato, ninho de rato.",
    "Casa de pais, escola de filhos.",
    "Casa de pobre, tacho de cobre.",
    "Casa de pombo, casa de tombo.",
    "Casa que não é ralhada, não é bem governada.",
    "Casamento, apartamento.",
    "Casarás e amansarás.",
    "Cava fundo em Novembro para plantares em Janeiro.",
    "Cavalo amarrado também pasta.",
    "Cavalo fouveiro, deixa o dono no terreiro.",
    "Cavalo que voa não quer espora.",
    "Cesteiro que faz um cesto faz um cento, dando-lhe verga e tempo.",
    "Céu escamado, ao terceiro dia molhado.",
    "Cevada loira, sardinha como toira.",
    "Choupana onde se ri vale mais que palácio onde se chora.",
    "Chovam trinta Maios e não chova em Junho.",
    "Chove, chove, galinha foge.",
    "Chuva de ascensão dá palhinhas e pão.",
    "Chuva de Junho, peçonha do mundo.",
    "Chuva de S. João talha o vinho e não dá pão.",
    "Chuva em Dia das Candeias, ano de ribeiras cheias.",
    "Chuva em Janeiro e não frio, dá riqueza no estio.",
    "Colcha feita, noivo à espreita.",
    "Com a mulher e o dinheiro, não zombes companheiro.",
    "Com direito por teu lado, nunca receies dar brado.",
    "Com o fogo não se brinca.",
    "Com papas e bolos se enganam os tolos.",
    "Com vento se limpa o trigo, e os vícios com castigo.",
    "Come pouco e bebe pouco, e dormirás como um louco.",
    "Comer e coçar, o mal é começar.",
    "Comer laranjas em Janeiro, é dar que fazer ao coveiro.",
    "Comida fina em copos grossos faz mal aos ossos.",
    "Como canta o galo velho, assim cantará o novo.",
    "Como fizeres, assim acharás.",
    "Contra a força, não há resistência.",
    "Contra factos, não há argumentos.",
    "Criado que faz o seu dever, orelhas de burro deve ter.",
    "Cu de Cão e nariz de gente, nunca está quente.",
    "Cuidados e caldos de Galinha, nunca fizeram mal a ninguém.",
    "Dá Deus nozes, a quem não tem dentes.",
    "Da discussão nasce a luz.",
    "Dá duas vezes, quem prontamente dá.",
    "Da flor de Janeiro, ninguém enche o celeiro.",
    "Dádiva de ruim, a seu dono se parece.",
    "Dar a César o que é de César, dar a Deus o que é de Deus.",
    "De boas intenções, está o Inferno cheio.",
    "De Espanha, nem bom vento nem bom casamento.",
    "De lautas ceias, estão as sepulturas cheias.",
    "De livro fechado, não sai letrado.",
    "De manhã a manhã, perde o Carneiro a lã.",
    "De manhã ao monte, de tarde à fonte.",
    "De médico e de louco, todos temos um pouco.",
    "De noite todos os gatos são pardos.",
    "De pequenino se torce o pepino.",
    "De rico a soberbo, não há palmo inteiro.",
    "De S.ª Catarina ao Natal, um mês igual.",
    "Defeitos do meu amigo, lamento mas não maldigo.",
    "Deitar cedo e cedo erguer, dá saúde e faz crescer.",
    "Depois da batalha aparecem os valentes.",
    "Depois da tempestade vem a bonança.",
    "Depois de casa roubada trancas à porta.",
    "Depois de S. Vicente já se pode enganar toda a gente.",
    "Depois do burro morto, cevada ao rabo.",
    "Depressa e bem, não há quem.",
    "Desmanchar e fazer tudo é fazer.",
    "Deus ajuda quem trabalha, que é o capital que menos falha.",
    "Deus ajudando vai em Julho mereando.",
    "Deus dá o frio conforme a roupa.",
    "Deus é bom e o diabo não é mau.",
    "Deus escreve direito por linhas tortas.",
    "Deus nos livre dos maus vizinhos de ao pé da porta.",
    "Deus quer, o Homem sonha, a obra nasce.",
    "Deus vê o que o Diabo esconde.",
    "Devagar se vai ao longe.",
    "Dezembro com Junho ao desafio, traz Janeiro frio.",
    "Dezembro frio, calor no estio.",
    "Dia de S. Barnabé, sega-se a palma do pé.",
    "Dia de S. Silvestre, quem tem carne que lhe preste.",
    "Dinheiro compra pão, mas não compra gratidão.",
    "Dinheiro e santidade, a metade da metade.",
    "Dinheiro emprestado, anda mal parado.",
    "Dinheiro emprestaste, inimigo criaste.",
    "Dinheiro esquecido, nem é pago nem agradecido.",
    "Dinheiro não traz felicidade.",
    "Diz o roto ao nu: porque não te vestes tu?",
    "Diz-me com quem andas, dir-te-ei quem és.",
    "Do Natal à Sta. Luzia, cresce um palmo em cada dia.",
    "Do trabalho e experiência, aprendeu o Homem a ciência.",
    "Dos 15 aos 20, caso com quem o meu pai quiser; dos 20 aos 25 é com quem eu quiser; depois dos 25, venha quem vier, não fica sem mulher.",
    "Dos enganos vivem os Escrivães.",
    "Dos Santos ao Natal, é Inverno natural.",
    "Duro com duro, não faz bom muro.",
    "É mais fácil prometer que dar.",
    "É tarde para economia, quando a bolsa está vazia.",
    "Em Abril águas mil.",
    "Em Abril queima a velha o carro e o carril.",
    "Em Abril, cada pulga dá mil.",
    "Em Abril, lavra as altas, mesmo com água pelo machil.",
    "Em Abril, vai onde deves ir, mas volta ao teu covil.",
    "Em Agosto, antes vinagre do que mosto.",
    "Em Agosto, nem vinho nem mosto.",
    "Em Agosto, Sardinhas e mosto.",
    "Em ano chuvoso, até o diligente é preguiçoso.",
    "Em ano geado, não há pão dobrado.",
    "Em casa de ferreiro, espeto de pau.",
    "Em casa de Gonçalo, pode mais a galinha que o galo.",
    "Em casa em que não há pão todos ralham e ninguém tem razão.",
    "Em Dezembro, treme de frio cada membro.",
    "Em dia de festa a barriga atesta.",
    "Em dia de S. Matias, começam as enxertias.",
    "Em Fevereiro, chega-te ao lameiro.",
    "Em Fevereiro, chuva; em Agosto, uva.",
    "Em Janeiro saltinho de carneiro.",
    "Em Janeiro sobe ao outeiro; se vires verdejar, põe-te a chorar, se vires nevar, põe-te a cantar.",
    "Em Janeiro uma hora por inteiro e, quem bem olhar, hora e meia há-de achar.",
    "Em Janeiro, cada Ovelha com seu Cordeiro.",
    "Em Janeiro, nem Galgo lebreiro, nem Açor perdigueiro.",
    "Em Janeiro, seca a Ovelha no fumeiro.",
    "Em Janeiro, sete capelos e um sombreiro.",
    "Em Janeiro, um Porco ao sol e outro ao fumeiro.",
    "Em Maio queima-se a cereja ao borralho.",
    "Em Maio, já a velha aquece o palácio.",
    "Em Maio, nem à porta de casa saio.",
    "Em Março, esperam-se as rocas e sacham-se as hortas.",
    "Em Março, tanto durmo como faço.",
    "Em Novembro, prova o vinho e planta o cebolinho.",
    "Em Outubro sê prudente: guarda pão, guarda semente.",
    "Em Outubro, o fogo ao rubro.",
    "Em Outubro, paga tudo.",
    "Em princípio de Maio, corre o Lobo e o Veado.",
    "Em Roma sê romano.",
    "Em Setembro, ardem os montes, secam-se as fontes.",
    "Em tempo de Figos, não há amigos.",
    "Em tempo de guerra todo o buraco é trincheira.",
    "Em tempo de guerra, não se limpam as armas.",
    "Em terra de cegos, quem tem um olho é Rei.",
    "Enquanto se capa, não se assobia.",
    "Enquanto se cava na vinha, não se cava no bacelo.",
    "Entradas de Leão, saídas de Sendeiro.",
    "Entre marido e mulher não metas a colher.",
    "Entrudo borralheiro, Páscoa soalheira.",
    "Escândalo aparta amor.",
    "Escuta cem vezes, e fala uma só.",
    "Escuta o conselho dos outros e segue o teu.",
    "Espera de teus filhos o que a teus pais fizeres.",
    "Este mundo é uma bola; quem anda nela é que se amola.",
    "Fala pouco e bem, ter-te-ão por alguém.",
    "Fala-se no diabo e aparece-lhe o rabo.",
    "Falai no mau, aparelhai o pau.",
    "Falar sem cuidar, é atirar sem apontar.",
    "Faz o que digo, não faças o que faço.",
    "Faz da noite, noite; e do dia, dia e viverás com alegria.",
    "Fazer bem a vilão ruim é lançar água em cesto roto.",
    "Feno alto ou baixo, em Junho é cegado.",
    "Fevereiro é dia, e logo é Santa Luzia.",
    "Fevereiro enxuto, rói mais pão do que quantos ratos há no mundo.",
    "Fevereiro quente, traz o diabo no ventre.",
    "Fevereiro recouveiro, afaz a perdiz ao poleiro.",
    "Fia-te na Virgem e não corras e logo vês o trambolhão que levas.",
    "Fiandeira não ficaste, pois em Maio não fiaste.",
    "Fidalgos, galgos e pardais são três espécies de animais.",
    "Filho de burro não pode ser cavalo.",
    "Filho de peixe sabe nadar.",
    "Filho és pai serás, assim como fizeres assim acharás.",
    "Filho que pais amargura, jamais conte com ventura.",
    "Filho sem dor, mãe sem amor.",
    "Filhos criados, trabalhos dobrados.",
    "Filhos das minhas filhas, meus netos são. Filhos dos meus filhos serão ou não.",
    "Flor ao peito, asno perfeito.",
    "Formosura, pouco dura.",
    "Fui a casa da minha vizinha, envergonhei-me; vim para a minha e governei-me.",
    "Gado de bico, nunca deixou ninguém rico.",
    "Gaivotas em terra temporal no mar.",
    "Galinha cantadeira é pouco poedeira.",
    "Galinha do mato, não quer capoeira.",
    "Galinha gorda ao maltês, ou podre, ou choca de um mês.",
    "Galinha que canta, faca na garganta.",
    "Galinhas de S. João, no Natal ovos dão.",
    "Galo cantador é pouco galador.",
    "Galo que acompanha pato morre afogado.",
    "Ganhá-lo como um preto, gastá-lo como um fidalgo.",
    "Ganhai o que souberdes e poupai o que puderdes.",
    "Gato escaldado, de água fria tem medo.",
    "Goraz de Janeiro vale dinheiro.",
    "Gordura, é formosura.",
    "Grandes discursos não provam grande sabedoria.",
    "Grão a grão, enche a galinha o papo.",
    "Guarda de comer, não guardes de fazer.",
    "Guarda hoje o que não precisas, que amanhã pode servir-te.",
    "Guarda o melhor saio para Maio.",
    "Guarda o que não presta, terás o que é preciso.",
    "Guarda prado, criarás gado.",
    "Guarda-te do homem que não fala e do cão que não ladra.",
    "Guardado está o bocado para quem o há-de comer.",
    "Há males que vêm por bem.",
    "Há mar e mar, há ir e voltar.",
    "Há mil modos de morrer e um só de nascer.",
    "Haja fartura, que a fome ninguém a atura.",
    "Homem folgazão, no trabalho sonolento.",
    "Homem necessitado, cada ano apedrejado.",
    "Homem pequenino, ou velhaco ou dançarino.",
    "Homem prevenido vale por dois.",
    "Hora a hora, Deus melhora.",
    "Imita a formiga e viverás sem fadiga.",
    "Inverno de Março e seca de Abril, deixam o lavrador a pedir.",
    "Ira e cobiça, não queiras havê-las por companheiras.",
    "Janeiro fora, cresce uma hora.",
    "Janeiro geoso e Fevereiro chuvoso fazem o ano formoso.",
    "Janeiro molhado, se não cria o pão, cria o gado.",
    "Janeiro molhado, se não é bom para o pão, não é mau para o gado.",
    "Janeiro quente, traz o Diabo no ventre.",
    "Janeiro tem uma hora por inteiro.",
    "Julho quente, seco e ventoso, trabalha sem repouso.",
    "Junho calmoso, ano formoso.",
    "Junho floreiro, paraíso verdadeiro.",
    "Junho, dorme-se sobre o punho.",
    "Junho, foice em punho.",
    "Junta-te aos bons e serás como eles; junta-te aos maus e serás pior do que eles.",
    "Lá vai o mal, onde comem o ovo sem sal.",
    "Ladrão que rouba a ladrão tem cem anos de perdão.",
    "Lágrimas de herdeiros, sorrisos sorrateiros.",
    "Lenha de figueira, rica de fumo, fraca de madeira.",
    "Leste escuro, Sol seguro.",
    "Livra-te do homem que não fala e do cão que não ladra.",
    "Logo que Outubro venha, procura a lenha.",
    "Longe da vista, longe do coração.",
    "Lua cheia, abóboras como areia.",
    "Lua nova trovejada, trinta dias é molhada.",
    "Luar de Janeiro não tem parceiro; mas lá vem o de Agosto que lhe dá no rosto.",
    "Lugar ventoso, lugar sem repouso.",
    "Macaco velho, não trepa galho seco.",
    "Maio couveiro não é vinhateiro.",
    "Maio frio e Junho quente: bom pão, vinho valente.",
    "Maio hortelão, muita palha e pouco grão.",
    "Maio pardo e ventoso faz o ano formoso.",
    "Mais depressa se apanha um mentiroso que um coxo.",
    "Mais fere a palavra do que a espada.",
    "Mais homens se afogam num copo do que no mar.",
    "Mais se tira com amor do que com dor.",
    "Mais vale burro vivo do que sábio morto.",
    "Mais vale cair em graça, do que ser engraçado.",
    "Mais vale cão vivo, que leão morto.",
    "Mais vale inveja que pena.",
    "Mais vale ir, do que mandar.",
    "Mais vale lavrar o nosso ao longe do que o alheio ao perto.",
    "Mais vale pão duro, que figo maduro.",
    "Mais vale penhor na arca, do que fiador na praça.",
    "Mais vale perder um minuto na vida do que a vida num minuto.",
    "Mais vale prevenir, que remediar.",
    "Mais vale prudência que ciência.",
    "Mais vale quem Deus ajuda do que quem muito madruga.",
    "Mais vale recusar com graça, do que dar com grosseria.",
    "Mais vale só, que mal acompanhado.",
    "Mais vale tarde do que nunca.",
    "Mais vale um cavalo com uma cela, do que três celas sem cavalo.",
    "Mais vale um farto, que dois famintos.",
    "Mais vale um gosto na vida, que três reis na algibeira.",
    "Mais vale um pássaro na mão, que dois a voar.",
    "Mais vale um que saiba mandar, do que cem a trabalhar.",
    "Mais vale um sim tardio do que um não vazio.",
    "Mais vale um toma do que dois te darei.",
    "Mais vale um vizinho à mão, do que ao longe o nosso irmão.",
    "Mais viver, mais aprender.",
    "Mal alheio, pesa como um cabelo.",
    "Mal haja quem de mim mal diz, mais quem mo traz ao nariz.",
    "Mal por mal, antes cadeia que hospital."
  ],
  pt2: [
    "Mal vai Portugal se não há três cheias antes de Natal.",
    "Malha o ferro enquanto está quente.",
    "Manda e faz: servido serás.",
    "Manda quem pode. Obedece quem deve.",
    "Manhã de açougue: quem mal fala, pior ouve.",
    "Mãos frias amores todos os dias.",
    "Mãos frias, coração quente, amor para sempre.",
    "Mãos quentes amores ausentes.",
    "Março duvidoso, S. João farinhoso.",
    "Março, marçagão, manhãs de Inverno e tardes de Verão.",
    "Meia vida é a candeia e o vinho outra meia.",
    "Mel, se o achaste come o que baste.",
    "Melhor é o ano tardio, do que o vazio.",
    "Mentir, nem zombando.",
    "Mocidade ociosa, traz velhice vergonhosa.",
    "Morra a pessoa mas fique a fama.",
    "Morra Marta, mas morra farta.",
    "Morrer por morrer, morra o meu pai que é mais velho.",
    "Morreu o bicho, acabou-se a peçonha.",
    "Morte com honra, não desonra.",
    "Morte desejada, é vida dobrada.",
    "Morto por morto, antes a velha que o porco.",
    "Muda-se de moleiro, não se muda de ladrão.",
    "Mudam-se os tempos, mudam-se as vontades.",
    "Muita gente junta não se salva.",
    "Muitas vezes se perde por preguiça o que se ganha por justiça.",
    "Muito atura quem precisa.",
    "Muito esquece a quem não sabe.",
    "Muito falar, pouco acertar.",
    "Muito falar, pouco pensar.",
    "Muito gasta o que vai e vem, mas mais gasta o que se detém.",
    "Muito pode a velhinha com o que leva para a sua casinha.",
    "Muito riso, pouco siso.",
    "Muitos conhecidos, poucos amigos.",
    "Muitos poucos, fazem muito.",
    "Mulher doente, mulher para sempre.",
    "Mulher e sardinha querem-se da pequenina.",
    "Mulher que assobia, ou capa porcos ou atraiçoa o marido.",
    "Mulher que assobia, ou é cabra ou é vadia.",
    "Mulher sardenta, mulher rabugenta.",
    "Na casa cheia, depressa se faz a ceia.",
    "Na casa deste home quem não trabalha não come.",
    "Na casa onde há dinheiro deve haver um só caixeiro.",
    "Na necessidade prova-se a amizade.",
    "Na prisão e no hospital, vês quem te quer bem e quem te quer mal.",
    "Na terra onde fores viver faz como vires fazer.",
    "Não acordes o gato que dorme.",
    "Não adianta chorar sobre o leite derramado.",
    "Não contes os pintos senão depois de nascidos.",
    "Não cresce erva em caminho calcado.",
    "Não dá a bota com a perdigota.",
    "Não deites foguetes antes da festa.",
    "Não deixes para amanhã o que podes fazer hoje.",
    "Não desejes mal a ninguém, que o teu mal pelo caminho vem.",
    "Não é bom o mosto colhido em Agosto.",
    "Não é com vinagre que se apanham moscas.",
    "Não é por grandes orelhas que o burro vai à feira.",
    "Não é por muito madrugar que amanhece mais cedo.",
    "Não faças nada antes de consultar a almofada.",
    "Não há amor como o primeiro.",
    "Não há atalho sem trabalho.",
    "Não há ausentes sem culpas, nem presentes sem desculpas.",
    "Não há bacorinho sem seu S. Martinho.",
    "Não há bela sem senão.",
    "Não há bem que sempre dure nem mal que nunca acabe.",
    "Não há boa terra sem bom lavrador.",
    "Não há duas sem três.",
    "Não há Entrudo sem Lua Nova nem Páscoa sem Lua Cheia.",
    "Não há fome que não dê em fartura.",
    "Não há fumo sem fogo.",
    "Não há guerra de mais aparato do que muitas mãos no mesmo prato.",
    "Não há luar como o de Janeiro nem amor como o primeiro.",
    "Não há maior amigo do que Julho com seu trigo.",
    "Não há mal que bem não traga.",
    "Não há mal que sempre dure nem bem que não se acabe.",
    "Não há mau tempo senão quando faz vento.",
    "Não há mês mais irritado do que Abril zangado.",
    "Não há onde o filho fique bem, como no colo da mãe.",
    "Não há pior cego do que aquele que não quer ver.",
    "Não há regra sem excepção.",
    "Não há roca sem fuso.",
    "Não há Sábado sem Sol, nem Domingo sem Missa, nem Segunda sem preguiça.",
    "Não hajas dó de quem tem muita roupa e faz má cama.",
    "Não mates mais do que podes salgar.",
    "Não medram as galinhas onde a raposa mora.",
    "Não peças a quem pediu nem sirvas a quem serviu.",
    "Não ponhas o carro à frente dos bois.",
    "Não se deve contar com um ovo quando ainda está dentro da galinha.",
    "Não se falar ao mestre do que ele ensina mal.",
    "Não se fazem omeletes sem partir ovos.",
    "Não se foge ao destino.",
    "Não se pescam trutas a bragas enxutas.",
    "Nao se pode ter sol na eira e chuva no nabal.",
    "Não suba o sapateiro além da chinela.",
    "Não te rias da caveira, que um dia nela te vais tornar.",
    "Não ter eira nem beira, nem raminho na figueira.",
    "Não tira bom resultado, quem vai onde não é chamado.",
    "Não tornes por detrás, pois é fraqueza desistir-se de coisa começada.",
    "Nas costas dos outros se vêm as nossas.",
    "Nasce erva em Março, ainda que lhe dêem com um maço.",
    "Natal a assoalhar e Páscoa ao mar.",
    "Natal à segunda-feira: Lavrador alarga a eira.",
    "Natal na praça e Páscoa em casa.",
    "Nem em Agosto caminhar, nem em Dezembro marear.",
    "Nem mesa sem pão, nem exército sem capitão.",
    "Nem no Inverno sem capa, nem no Verão sem cabaça.",
    "Nem sempre, nem nunca.",
    "Nem só de pão vive o homem.",
    "Nem tudo o que abana cai.",
    "Nem tudo o que luz é ouro, nem tudo o que alveja é prata.",
    "Nem tudo o que vem à rede é peixe.",
    "Neve em Fevereiro, presságio de mau celeiro.",
    "Nevoeiro de S. Pedro, põe em Julho o vinho a medo.",
    "Nevoeiro na serra, chuva na terra.",
    "Ninguém está bem com a sorte que tem.",
    "Ninguém se ria com o mal do vizinho, que o seu pode vir a caminho.",
    "Ninguém toque na ferida quando ainda sangra e está dorida.",
    "Ninho feito, Pega morta.",
    "No amor, quem foge é o vencedor.",
    "No aperto do perigo, conhece-se o amigo.",
    "No Carnaval nada parece mal.",
    "No dia da cozedura, até as aranhas ficam fartas.",
    "No dia de S. Lourenço vai à vinha e enche o lenço.",
    "No dia de S. Martinho vai à adega e prova o vinho.",
    "No dia de S. Martinho, mata o teu porco e prova o teu vinho.",
    "No dia de S. Martinho, lume, castanhas e vinho.",
    "No dia de Santiago pinta o bago.",
    "No dia de Santiago vai à vinha e prova o bago.",
    "No meio está a virtude.",
    "No melhor pano cai a nódoa.",
    "No minguante de Janeiro, corta o madeiro.",
    "No Natal à janela, na Páscoa à panela.",
    "No Outono o Sol tem sono.",
    "No poupar é que está o ganho.",
    "No princípio ou no fim, costuma Abril a ser ruim.",
    "No S. João, a sardinha pinga no pão.",
    "No tempo do cuco, tanto está molhado como enxuto.",
    "Noite aqui, noite em casa.",
    "Norte frio, água no rio.",
    "Nunca de corvo bom ovo.",
    "Nunca digas desta água não beberei.",
    "Nunca falta um chinelo velho para um pé manco.",
    "Nuvens em Setembro: chuva em Novembro e neve em Dezembro.",
    "O alheio chora o seu dono.",
    "O barato sai caro.",
    "O Bem soa, o Mal voa.",
    "O bom filho à casa torna.",
    "O bom julgador por si se julga.",
    "O bom junto ao pequeno fica maior, e junto ao mau fica pior.",
    "O cão com raiva, do seu dono trava.",
    "O casamento e a mortalha no céu se talha.",
    "O descuidado sempre é necessitado.",
    "O Diabo cobre com uma manta e descobre com um chocalho.",
    "O fraco ofendido atraiçoa e o forte perdoa.",
    "O fruto proibido é o mais apetecido.",
    "O futuro a Deus pertence.",
    "O ganho e a lazeira andam de feira em feira.",
    "O hábito não faz o monge.",
    "O ladrão volta sempre ao local do crime.",
    "O mal e o bem à face vêm.",
    "Ó mar alto, ó mar alto, ó mar alto sem ter fundo; mais vale andar no mar alto do que nas bocas do mundo.",
    "O mau é ter mais olhos do que barriga.",
    "O medo guarda a vinha.",
    "O Melão e a Mulher são maus de conhecer.",
    "O mês de Agosto será gaiteiro, se for bonito o 1º de Janeiro.",
    "O morgado e a morgada e o resto da manada não prestam para nada.",
    "O necessário deleita, o desnecessário atormenta.",
    "O novo por não saber e o velho por não poder deitam tudo a perder.",
    "O olho do dono, engorda o cavalo.",
    "O pouco basta, e o muito se gasta.",
    "O primeiro milho é para os pardais.",
    "O prometido é devido.",
    "O que a água dá, a água levará.",
    "O que anda a cavalo vive pouco e o que anda a pé contam-no por morto.",
    "O que é demais molesta.",
    "O que está feito, feito está.",
    "O que não mata, engorda.",
    "O que não tem remédio, remediado está.",
    "O que o juízo dos pais acumula, a loucura dos filhos desbarata.",
    "O que para uns é mel, para outros é fel.",
    "O que tem de ser, tem muita força.",
    "O rabo, sempre cheira ao que larga.",
    "O Robalo, quem o quiser há-de escamá-lo.",
    "O Saber não ocupa lugar.",
    "O segredo é a alma do negócio.",
    "O seguro morreu de velho.",
    "O seu a seu dono.",
    "O Sogro e o Furão só dão interesse debaixo do chão.",
    "O sol quando nasce é para todos.",
    "O Surdo faz falar o Mudo.",
    "O tempo é o melhor juiz.",
    "O tempo em Fevereiro enganou a Mãe ao soalheiro.",
    "O tempo perdido nunca se recupera.",
    "O trabalho do menino é pouco, mas quem o despreza é louco.",
    "O Verão colhe e o Inverno come.",
    "O Vinho e o Amigo, do mais antigo.",
    "Obra de vilão, deitar pedra e esconder a mão.",
    "Ofende os bons quem poupa os maus.",
    "Olhar para a uva não mata a sede.",
    "Olho azul em português não é sinal de boa rês.",
    "Olho por olho, dente por dente.",
    "Olhos que não vêm, coração que não sente.",
    "Oliveira de meu avô, Figueira de meu pai, vinha que eu plantar.",
    "Onde fores ter, faz como vires fazer.",
    "Onde se chora não cantes.",
    "Onde vai o emprestado, que venha remediado.",
    "Orelha de homem, nariz de mulher e focinho de cão, nunca viram o Verão.",
    "Os amigos são para as ocasiões.",
    "Os cães ladram mas a caravana passa.",
    "Os dias do Natal são saltos de pardal.",
    "Os erros dos médicos a terra os cobre.",
    "Os homens não se medem aos palmos.",
    "Os males dos nossos avós, fazem-no eles e pagamo-los nós.",
    "Os olhos pedem mais do que a barriga aguenta.",
    "Ouriços do S. João são do tamanho dum botão.",
    "Ouro adquirido, sono perdido.",
    "Outubro meio chuvoso, torna o lavrador venturoso.",
    "Outubro quente traz o diabo no ventre.",
    "Outubro suão, negaças de Verão.",
    "Ouve tudo bem, diz o que lhe convém.",
    "Ovelha que berra, bocado que perde.",
    "Pelo S. João, Perdigoto na mão.",
    "Pelo S. Mateus, pega nos bois e lavra com Deus.",
    "Para trás mija a burra.",
    "Paga o justo pelo pecador.",
    "Pagar e morrer, é a última coisa a fazer.",
    "Pai rico, filho nobre, neto pobre.",
    "Pais galegos, filhos barões, netos ladrões.",
    "Pais impertinentes fazem filhos desobedientes.",
    "Palavra de Rei, não volta atrás.",
    "Palavras de mel, coração de fel.",
    "Palavras, leva-as o vento.",
    "Panela velha faz boa sopa.",
    "Pão com olhos, queijo sem olhos e vinho que espirre para os olhos.",
    "Pão proibido abre o apetite.",
    "Pão que sobre, Carne que baste e Vinho que falte.",
    "Para a fome não há mau pão.",
    "Para baixo todos os Santos ajudam.",
    "Para bom entendedor, meia palavra basta.",
    "Para dar e para ter, muito rico é preciso ser.",
    "Para ensinar, é preciso aprender.",
    "Para grandes males, grandes remédios.",
    "Para Junho guarda um toco e uma pinha, e a velha que o dizia guardados os tinha.",
    "Para lá do Marão, mandam os que lá estão.",
    "Para mal que hoje acaba, não é remédio o de amanhã.",
    "Para ovos frigir, temos de os partir.",
    "Para palavras loucas, orelhas moucas.",
    "Para parte de Fevereiro, guarda lenha de Quinteiro.",
    "Parar é morrer.",
    "Páscoa alta, chumbo na malta.",
    "Páscoa em Março, ou fome ou mortaço.",
    "Pássaro do campo cedo madruga.",
    "Patrão fora, feriado na loja.",
    "Pau deitado não chama trovoada.",
    "Pau que nasce torto jamais se endireita",
    "Pedir a avarento, é caçar no mar.",
    "Pedra que rola, não cria musgo.",
    "Peixe não puxa carroça.",
    "Pela boca morre o peixe.",
    "Pelas costas dos outros se vêm as nossas.",
    "Pelo andar da carruagem vê-se logo quem lá vai dentro.",
    "Pelo S. Martinho todo o mosto é bom vinho.",
    "Pelo S. Martinho, deixa a água pró moinho.",
    "Pelo S. Matias começam as enxertias.",
    "Pelo Santiago, cada pinga vale um cruzado.",
    "Pelo voo se conhece a ave.",
    "Pelos Santos neve nos campos.",
    "Pelos Santos trigo semeado, fruto arrancado.",
    "Perdido por cem, perdido por mil.",
    "Pintainho de Janeiro, vai com a mãe ao poleiro.",
    "Poda-me em Janeiro, empa-me em Março e verás o que te faço.",
    "Podar em Março é ser madraço.",
    "Polidez, pouco custa e muito vale.",
    "Por casar nunca ninguém ficou, não foi com quem quis, foi com quem calhou.",
    "Por cima de melão, vinho de tostão.",
    "Por falar se ganha, por falar se perde.",
    "Por morrer uma andorinha não acaba a Primavera.",
    "Por S. Gil, adoba teu candil.",
    "Por S. Mateus faz conta das ovelhas que os borregos são teus.",
    "Por S. Matias, noites iguais aos dias.",
    "Por S. Simão e S. Judas colhidas são as uvas.",
    "Por S. Vicente, toda a água é quente.",
    "Por Santa Maria de Agosto repasta a vaca um pouco.",
    "Porcos com frio e homens com vinho fazem grande ruído.",
    "Pouco a pouco fia a velha o copo.",
    "Pouco e em paz muito se faz.",
    "Poupar enquanto há; não havendo, poupado está.",
    "Preso por ter cão e preso por não ter.",
    "Presunção e água benta cada qual toma a que quer.",
    "Primeiro de Agosto, primeiro de Inverno.",
    "Primeiros trovões e relâmpagos, fertilidade de frutos e esterilidade de campos.",
    "Quem ri por último ri melhor.",
    "Quando a esmola é grande, o santo desconfia.",
    "Quando a esmola é muita, o pobre desconfia.",
    "Quando chove antes da missa, toda a semana borriça.",
    "Quando chove em Agosto, não metas teu dinheiro em mosto.",
    "Quando é de morte o mal, não há médico para curar tal.",
    "Quando é velho o cão, se ladra é porque tem razão.",
    "Quando em Março arrulha a perdiz, ano feliz.",
    "Quando está fora o gato folga o rato.",
    "Quando Maio chegar, quem não arou tem de arar.",
    "Quando mal, nunca pior.",
    "Quando mija um português, mijam logo dois ou três.",
    "Quando minguar a Lua não comeces coisa alguma.",
    "Quando não chove em Fevereiro, nem prados nem centeio.",
    "Quando o ano é de leite, até os bodes o dão.",
    "Quando o burro é jeitoso, qualquer albarda lhe fica bem.",
    "Quando o pobre come galinha, um dos dois está doente.",
    "Quando Outubro for erveiro, Guarda para Março o palheiro.",
    "Quando se declara a guerra, o Diabo alarga o Inferno.",
    "Quando um burro zurra, os outros abaixam as orelhas.",
    "Quando um cai, todos o pisam.",
    "Quando vem Março ventoso, Abril sai chuvoso.",
    "Quanto maior a nau, maior a tormenta.",
    "Quanto mais alto se sobe, maior o trambolhão.",
    "Quanto mais barato estiver o pão, melhor canta o coração.",
    "Quanto mais conheço os homens, mais gosto dos cães.",
    "Quanto mais depressa, mais devagar.",
    "Quanto tens, quanto vales.",
    "Queijo com pão faz homem são.",
    "Queimada a casa, acudir com água.",
    "Queira ou não queira, o burro há-de ir à feira.",
    "Quem a boa árvore se encosta, boa sombra o acolhe.",
    "Quem a muitos há-de manter, muito há-de ter.",
    "Quem abana, nem sempre cai.",
    "Quem acompanha com coxo, ao terceiro dia coxeia.",
    "Quem ama a Beltrão, ama o seu cão.",
    "Quem anda à chuva, molha-se.",
    "Quem ao comer sua, ao trabalho amua.",
    "Quem ao moinho vai, enfarinhado sai.",
    "Quem aos vinte não é, aos trinta não tem, aos quarenta não é ninguém.",
    "Quem bebe no S. Martinho, faz de velho e de menino.",
    "Quem bem ama não esquece.",
    "Quem bem nada não se afoga.",
    "Quem boa cama fizer, nela se há-de deitar.",
    "Quem brinca com o fogo queima-se.",
    "Quem cabritos vende e cabras não tem, dalgum lado lhe vem.",
    "Quem caça de coração é o dono do furão.",
    "Quem cala, consente.",
    "Quem cansa sempre alcança.",
    "Quem canta antes do almoço, chora antes do Sol posto.",
    "Quem canta, seu mal espanta.",
    "Quem casa filha, depenado fica.",
    "Quem casa, quer casa.",
    "Quem com farelos se mistura, porcos o comem.",
    "Quem com ferros mata, com ferros morre.",
    "Quem com os braços não pode, com os dentes acode.",
    "Quem com porcos sonha, até o mato lhe ronca.",
    "Quem come carne na vespera de Natal, ou é burro ou animal.",
    "Quem come fel, não pode cuspir mel.",
    "Quem compra barato, compra duas vezes.",
    "Quem compra terras, compra guerras.",
    "Quem confessa a verdade, não merece castigo.",
    "Quem conhece o seu Coração, desconfia dos seus olhos.",
    "Quem conta um conto, acrescenta-lhe um ponto.",
    "Quem convida de véspera, não quer que vá à festa.",
    "Quem corre por gosto, não cansa.",
    "Quem dá aos pobres, empresta a Deus.",
    "Quem dá e volta a tirar ao Inferno vai parar.",
    "Quem dá o pão, dá a educação.",
    "Quem dá o que tem, a pedir vem.",
    "Quem deixa o certo pelo incerto, ou é tolo ou pouco esperto.",
    "Quem desconfia, não é de confiar.",
    "Quem desdenha quer comprar.",
    "Quem deve a Pedro e paga a Gaspar, volta a pagar.",
    "Quem dívidas não tem, com a sua consciência está bem.",
    "Quem diz tudo o que quer, ouve o que não gosta.",
    "Quem é desconfiado não é sério.",
    "Quem é pobre não tem vícios.",
    "Quem é surdo, guarda segredos.",
    "Quem em Abril não varre a eira e em Maio não rega a leira, anda todo o ano em canseira.",
    "Quem em Janeiro lavrar, tem sete pães para o jantar.",
    "Quem em Julho ara e fia, Ouro cria.",
    "Quem em Maio não merenda, aos finados se encomenda.",
    "Quem em Maio relva, não tem pão nem erva.",
    "Quem em Março come sardinha, em Agosto lhe pica a espinha.",
    "Quem em novo não trabalha, em velho come palha.",
    "Quem em ruim terra nascer, sempre para ela há-de pender.",
    "Quem empresta não melhora.",
    "Quem encontrou sem muito procurar, é porque muito procurou sem encontrar.",
    "Quem espera sempre alcança.",
    "Quem espera, desespera.",
    "Quem está de fora, não racha lenha.",
    "Quem está mal, que se mude.",
    "Quem está vivo, sempre aparece.",
    "Quem estraga velho, paga novo.",
    "Quem fala no barco, quer embarcar.",
    "Quem faz mal, espere outro tal.",
    "Quem faz o que pode, a mais não é obrigado.",
    "Quem feio ama, bonito lhe parece.",
    "Quem guarda acha e quem cria mata.",
    "Quem longe vai casar, ou é enganado ou vai enganar.",
    "Quem madruga, Deus ajuda.",
    "Quem mais alto sobe, ao mais baixo vem parar.",
    "Quem mais jura, mais mente.",
    "Quem mal anda, mal acaba.",
    "Quem mal entende, mal conta.",
    "Quem me repreende, do mal me defende.",
    "Quem meu filho beija, minha boca adoça.",
    "Quem muitas estacas estancha, alguma lhe há-de pegar.",
    "Quem muito apalpa pouco acerta.",
    "Quem muito chora, pouco mija.",
    "Quem muito dorme pouco aprende.",
    "Quem muito fala, pouco aprende.",
    "Quem muito se abaixa, o cu se lhe vê.",
    "Quem namora pelo fato, leva o Diabo ao contrato.",
    "Quem não aparece, esquece.",
    "Quem não arrisca, não petisca.",
    "Quem não chora não mama.",
    "Quem não come por ter comido, não é mal de grande perigo.",
    "Quem não confia, não é de confiar.",
    "Quem não cria, não tosquia.",
    "Quem não debulha em Agosto, debulha com mau rosto.",
    "Quem não deve, não teme.",
    "Quem não estorva, ajuda.",
    "Quem não estraga não estreia.",
    "Quem não governa a lenha, não governa a casa que tenha.",
    "Quem não lerda não medra.",
    "Quem não pede, não o ouve Deus.",
    "Quem não quer ser lobo, não lhe vista a pele.",
    "Quem não sabe ser caixeiro, que feche a loja.",
    "Quem não sabe, é como quem não vê.",
    "Quem não se fartou no comer, não se farta no lamber.",
    "Quem não se ri ao mês, ou é tolo ou quem o fez.",
    "Quem não se sente, não é filho de boa gente.",
    "Quem não tem bois, não promete carrada.",
    "Quem não tem bois, ou antes ou depois.",
    "Quem não tem cão caça com gato.",
    "Quem não tem dinheiro não tem vícios.",
    "Quem não tem marido, não tem amigo.",
    "Quem não tem padrinho, morre Moiro.",
    "Quem não tem vergonha todo o mundo é seu.",
    "Quem o alheio veste na praça o despe.",
    "Quem o inimigo poupa, nas mãos lhe morre.",
    "Quem parte e reparte e fica com a pior parte, ou é tolo ou não tem arte.",
    "Quem pássaros receia, milho não semeia.",
    "Quem pede a Pedro e paga a Gaspar, volta a pagar.",
    "Quem pega por moça, perde por força.",
    "Quem planta no Outono, leva um ano de abono.",
    "Quem poda em Março, vindima no regaço.",
    "Quem porfia, mata caça.",
    "Quem pouco sabe, depressa o reza.",
    "Quem primeiro alça, primeiro calça.",
    "Quem quer bom ervilhal, semeia-o antes de Natal.",
    "Quem quer festa, sua-lhe a testa.",
    "Quem quer sopas gordas, vaca nelas.",
    "Quem quer, vai; quem não quer, manda.",
    "Quem quiser bolota que a trepe.",
    "Quem quiser fazer uma viagem em paz, não leve mulher, nem cão, nem rapaz.",
    "Quem quiser luxo, que lhe custe.",
    "Quem quiser o alho cachapernudo, plante-o no mês do Entrudo.",
    "Quem sabe do barco é o barqueiro.",
    "Quem sabe falar, evita guerrilhar.",
    "Quem sai aos seus não degenera.",
    "Quem saiba e pense, vence e convence.",
    "Quem se deserda antes que morra, merece uma cachaporra.",
    "Quem se mete por atalhos, mete-se em trabalhos.",
    "Quem se pica cardos come.",
    "Quem se quer ver sempre se encontra.",
    "Quem se rala morre cedo.",
    "Quem se veste de ruim pano, veste-se duas vezes por ano.",
    "Quem semeia ventos, colhe tempestades.",
    "Quem seu amigo quiser conservar, com ele não há-de negociar.",
    "Quem só mata, morre cedo.",
    "Quem só uma ovelha tem, mil lobos a comem.",
    "Quem te avisa, teu amigo é.",
    "Quem tem amigos, não morre na cadeia.",
    "Quem tem amores, tem dores.",
    "Quem tem boca não manda soprar.",
    "Quem tem boca, vai a Roma.",
    "Quem tem calos, não se mete em apertos.",
    "Quem tem capa sempre escapa.",
    "Quem tem cu tem medo.",
    "Quem tem filhos tem cadilhos.",
    "Quem tem fome, cardos come.",
    "Quem tem medo fica em casa.",
    "Quem tem saúde e liberdade é rico e não o sabe.",
    "Quem tem sorte ao jogo não tem sorte aos amores.",
    "Quem tem telhados de vidro, não atira pedras ao do vizinho.",
    "Quem tem unhas é que toca viola.",
    "Quem tem vagar, faz colheres.",
    "Quem tudo quer vingar, cedo há-de acabar.",
    "Quem tudo quer, tudo perde.",
    "Quem vai à guerra, dá e leva.",
    "Quem vai ao mar avia-se em terra.",
    "Quem vai para a cama sem ceia, toda a noite rabeia.",
    "Quem vê caras não vê corações.",
    "Quem vier atrás, feche a porta.",
    "Quem vive no convento é que sabe o que se passa lá dentro.",
    "Querer é poder.",
    "Queres pasmar o teu vizinho? Lavra e esterca pelo S. Martinho.",
    "Queres um conselho, pede-o ao velho.",
    "Ramos molhados, anos melhorados.",
    "Rego aberto, meia jeira é.",
    "Ri-se o diabo quando o pobre dá ao farto.",
    "Rogos de rei, mandados são.",
    "Roma e Pavia não se fizeram num dia.",
    "Ruídos ao Nascente: desapõe os bois e foge sempre.",
    "S. João e S. Miguel passados, tanto manda o amo como o criado.",
    "S. Miguel passado, todo o amo é mandado.",
    "S. Miguel soalheiro, enche o celeiro.",
    "Saber esperar é uma grande virtude.",
    "Santos da Terra não fazem milagres.",
    "Sapato branco em Janeiro é sinal de pouco dinheiro.",
    "Sáveis por S. Marcos, enchem-se os barcos.",
    "Se a Senhora das Candeias rir, está o Inverno para vir.",
    "Se chover antes de missa, toda a semana borriça.",
    "Sê em Agosto cuidadoso e aguilhoa o preguiçoso.",
    "Se em Outubro te sentires gelado, lembra-te do gado.",
    "Se o Inverno não erra caminho, têmo-lo pelo S. Martinho.",
    "Se o sapo canta em Janeiro, guarda a palha no sendeiro.",
    "Se o velho pudesse e o novo quisesse, nada havia que não se fizesse.",
    "Se queres ser bom alheiro, planta alhos em Janeiro.",
    "Se queres ser bom milheiro, faz o alqueire em Janeiro.",
    "Se queres um bom alhal, semeia-o antes do Natal.",
    "Se queres ver o teu corpo, abre o teu porco.",
    "Se queres ver o teu marido morto, dá-lhe couves em Agosto.",
    "Seda em Janeiro, ou fantasia ou falta de dinheiro.",
    "Segundo lá escolhestes, assim cá vos contentai.",
    "Semana Santa molhada, terra alterada.",
    "Semeia e cria, e viverás com alegria.",
    "Setembro, ou seca as fontes ou leva as pontes.",
    "Por S. Simão, favas no chão.",
    "Sol de Junho, madruga muito.",
    "Tanta chuva pelas candeias, tantas abelhas pelas comeias.",
    "Tanta vez vai o rato ao moinho, que um dia fica lá com o focinho.",
    "Tantas cabeças, quantas sentenças.",
    "Tantas vezes vai o cântaro à fonte que um dia lá fica a asa.",
    "Tanto lês, que treslês.",
    "Tanto vale cada um na praça, quanto vale o que tem na caixa.",
    "Tantos dias de geada terá Maio, quantos de nevoeiro teve Fevereiro.",
    "Tão ladrão é o que vai à horta, como o que fica à porta.",
    "Tão ladrão é o que vai à vinha, como o que fica à espreita.",
    "Tem o porco meão pelo S. João.",
    "Tempo de Santa Luzia, cresce a noite, minga o dia.",
    "Tempo é dinheiro.",
    "Temporã é a castanha que por Março arrebenta.",
    "Todo o burro come palha, é preciso é saber dar-lha.",
    "Todos os caminhos vão dar à ponte, quando o rio vai de monte a monte.",
    "Todos os caminhos vão dar a Roma.",
    "Todos os pássaros comem trigo e quem paga é o pardal.",
    "Tostão a tostão se faz um milhão.",
    "Tristezas não pagam dívidas.",
    "Tudo em Novembro guardado; em casa ou arrecadado.",
    "Tudo está bem, quando acaba em bem.",
    "Um burro carregado de livros é um doutor.",
    "Um dia, não são dias.",
    "Um galo não canta no ovo.",
    "Um homem atrapalhado, é pior do que uma mulher bêbeda.",
    "Um mal nunca vem só.",
    "Um olho no burro, outro no cigano.",
    "Um olho no prato, outro no gato.",
    "Um rico avarento, não tem amigo nem parente.",
    "Um sabor tem cada caça, mas o porco cento alcança.",
    "Uma água de Maio e três de Abril valem por mil.",
    "Uma coisa pensa o Baio, outra pensa o selador.",
    "Uma maçã por dia, dá uma vida sadia.",
    "Uma mão lava a outra e as duas lavam a cara.",
    "Uma mentira repetida mil vezes torna-se verdade.",
    "Uns comem os figos, a outros rebentam-lhe os lábios.",
    "Vão os anéis mas fiquem os dedos.",
    "Vaso ruim não quebra.",
    "Vê-se na adversidade o que é a amizade.",
    "Velho casado com nova, filhos até à cova.",
    "Velho casado com nova, ou corno ou cova.",
    "Velho e namorado, cedo enterrado.",
    "Velhos são os trapos.",
    "Vem a guerra, vai a guerra, fica a terra.",
    "Vento de Ramos, vento do ano.",
    "Verdura de Janeiro, não vai a palheiro.",
    "Vindima molhada, pipa depressa despejada.",
    "Vinho verde em Janeiro, é mortalha no telheiro.",
    "Viver não custa, o que custa é saber viver.",
    "Voz corrente muito mente.",
    "Voz do povo, voz de Deus.",
    "Zangam-se as comadres, descobrem-se as verdades.",
    "Zurros de burro não chegam aos céus."
  ]
};

const start = async () => {
  await Promise.all(
    proverbs["pt2"].map(async (text, i) => {
      await axios({
        method: "post",
        url: "http://localhost:4000/proverbs",
        data: {
          text,
          lang: "pt"
        }
      })
        .then(response => {
          console.log(response.statusText, i);
        })
        .catch(error => {
          console.log(error, i);
        });
    })
  )
    .then(response => {
      console.log("Done!");
    })
    .catch(error => {
      console.log(error);
    });
};

start();
